import { PricingModel } from '@prisma/client';

export type AppSeed = {
  slug: string;
  name: string;
  tagline: string;
  saveTimeLabel: string;
  category: string;
  pricing: PricingModel;
  channels: string[];
  targetPersona: string;
  hookAngle: string;
  trustSignals: string[];
  difficulty: number;
  heatScore: number;
  screenshotUrls: string[];
  teardown: {
    painSummary: string;
    painScore: string;
    triggerScene: string;
    corePromise: string;
    coreLoop: string;
    keyConstraints: string[];
    mvpScope: string;
    dataInput: string;
    dataOutput: string;
    faultTolerance: string;
    coldStartStrategy: string;
    pricingLogic: string;
    competitorDelta: string;
    riskNotes: string;
    expansionSteps: string[];
    reverseIdeas: string[];
  };
  assets: {
    hasAgentsTemplate: boolean;
    hasSpecTemplate: boolean;
    hasPromptPack: boolean;
    agentsTemplate?: string;
    specTemplate?: string;
    promptPack?: string;
  };
};

export const appSeeds: AppSeed[] = [
  {
    slug: 'poop-map',
    name: 'Poop Map',
    tagline: '上厕所也能打卡，地图上全是你的战绩。',
    saveTimeLabel: '点一下记录，立刻生成一张可用晒的地图。',
    category: '居家生活',
    pricing: PricingModel.USAGE_BASED,
    channels: ['Google Play', '社交分享'],
    targetPersona: '爱玩梗、喜欢记录日常、愿意和朋友分享趣事的人',
    hookAngle: '把平时不好意思提的事，变成可用炫耀的收藏。',
    trustSignals: ['Google Play 上架'],
    difficulty: 2,
    heatScore: 82,
    screenshotUrls: [
      '/assets/projects/poop-map/screenshot-1.png',
      '/assets/projects/poop-map/screenshot-2.png',
      '/assets/projects/poop-map/screenshot-3.png',
      '/assets/projects/poop-map/screenshot-4.png',
      '/assets/projects/poop-map/screenshot-5.png',
    ],
    teardown: {
      painSummary: '这件每天必做的小事太无聊，从没想过还能这样玩。',
      painScore: '大频 / 小门槛 / 大传播',
      triggerScene: '刚做完这件"私事"，突然想记录一下，最好还能逗朋友一笑。',
      corePromise: '点一下就能在地图上留个标记，慢慢攒成一张独特的战绩图。',
      coreLoop: '发生了 -> 打个点 -> 地图多了个标记 -> 忍不住想分享给朋友 -> 下次继续攒。',
      keyConstraints: ['记录必须快', '反馈要就是时', '分享要有梗'],
      mvpScope: '地图打点、战绩统计、简单分享。',
      dataInput: '地点、时间、一次打点。',
      dataOutput: '一张越来越满的地图、累计数据、分享图。',
      faultTolerance: '没网也能记，分享失败图还在。',
      coldStartStrategy: '靠猎奇和好玩在社交平台传开。',
      pricingLogic: '免费玩，靠广告和大级功能赚钱。',
      competitorDelta: '别人教你怎么健康，这里只关心你的地图好不好看。',
      riskNotes: '题材敏感，平台审核可能卡。',
      expansionSteps: ['加好友互看', '点赞通知', '排行榜'],
      reverseIdeas: ['健康记录地图', '城市打卡挑战', '反差社交方式'],
    },
    assets: {
      hasAgentsTemplate: true,
      hasSpecTemplate: true,
      hasPromptPack: false,
      agentsTemplate: '# Poop Map 助手\n帮你记录、攒战绩、分享给朋友。',
      specTemplate: '# Poop Map 说明\n记录 -> 地图 -> 分享 -> 提醒。',
    },
  },
  {
    slug: 'countdown-reminders-and-timer',
    name: 'Countdown! Reminders and Timer',
    tagline: '重要日子直接贴在锁屏上，不用解锁就能看见。',
    saveTimeLabel: '不用打开 App，锁屏和桌面直接告诉你还剩多久。',
    category: '职场',
    pricing: PricingModel.PAID,
    channels: ['App Store', '组件推荐'],
    targetPersona: '总怕忘事、喜欢盯着目标倒数的人',
    hookAngle: '把倒计时塞进锁屏，变成每天自动提醒你的背景。',
    trustSignals: ['App Store 上架'],
    difficulty: 2,
    heatScore: 68,
    screenshotUrls: [
      '/assets/projects/countdown-reminders-and-timer/screenshot-1.jpg',
      '/assets/projects/countdown-reminders-and-timer/screenshot-2.jpg',
      '/assets/projects/countdown-reminders-and-timer/screenshot-3.jpg',
      '/assets/projects/countdown-reminders-and-timer/screenshot-4.jpg',
      '/assets/projects/countdown-reminders-and-timer/screenshot-5.jpg',
    ],
    teardown: {
      painSummary: '重要日子总忘，总在想"还剩多少天"但懒得点开 App 看。',
      painScore: '大频 / 中痛 / 中大付费',
      triggerScene: '刚想看某个日子还有多久，发现又要解锁、找 App、等加载。',
      corePromise: '把倒计时直接放到锁屏和桌面，抬眼就能看见。',
      coreLoop: '设个日子 -> 选个好看的组件样式 -> 放到锁屏 -> 每天自动看见 -> 想再加几个。',
      keyConstraints: ['样式要多', '刷新要和时', '看起来要舒服'],
      mvpScope: '创建倒计时、锁屏小组件、桌面小组件。',
      dataInput: '事件名字、目标日期。',
      dataOutput: '精确到秒的倒计时、百分比进度、好看的组件。',
      faultTolerance: '组件卡住时，打开 App 还能看。',
      coldStartStrategy: '靠锁屏截图和"每天看见"这个点吸引下载。',
      pricingLogic: '先付费下载，再卖好看的组件皮肤。',
      competitorDelta: '别人卖功能列表，这里卖的是"不用打开就能看到"。',
      riskNotes: '小组件竞争太卷，设计不好看就没人用。',
      expansionSteps: ['做分享卡片', '出情况模板', '加更多小工具'],
      reverseIdeas: ['会议倒计时墙', '吃饭决策倒计时', '项目里程碑墙'],
    },
    assets: {
      hasAgentsTemplate: true,
      hasSpecTemplate: true,
      hasPromptPack: false,
      agentsTemplate: '# Countdown 助手\n帮你把倒计时放到锁屏和桌面。',
      specTemplate: '# Countdown 说明\n事件 -> 组件 -> 进度 -> 提醒。',
    },
  },
  {
    slug: 'liteschedule',
    name: 'LiteSchedule',
    tagline: '把课表搬到锁屏、灵动岛和手表，抬眼就看。',
    saveTimeLabel: '让下一节课和课程相关待办随时显示在锁屏上。',
    category: '校园',
    pricing: PricingModel.PAID,
    channels: ['App Store', '校园社群'],
    targetPersona: '学生群体和需要抬眼看日程的人',
    hookAngle: '课表不打开 App 也能用，不用打开 App 就能看见。',
    trustSignals: ['App Store 上架'],
    difficulty: 2,
    heatScore: 63,
    screenshotUrls: [
      '/assets/projects/liteschedule/screenshot-1.jpg',
      '/assets/projects/liteschedule/screenshot-2.jpg',
      '/assets/projects/liteschedule/screenshot-3.jpg',
      '/assets/projects/liteschedule/screenshot-4.jpg',
    ],
    teardown: {
      painSummary: '上课前总要解锁、找 App、等加载才能看到下节课，太麻烦。',
      painScore: '大频 / 中痛 / 小学习成本',
      triggerScene: '上课前几分钟，用户想看下一节。',
      corePromise: '课表、提醒和作业在锁屏和一直显示在锁屏。',
      coreLoop: '导入课表 -> 随时看 -> 关联作业 -> 一直提醒。',
      keyConstraints: ['足够干净', '入口够近', '不打扰'],
      mvpScope: '课表展示、Today 视图、作业挂课程。',
      dataInput: '课程、时间、地点、待办。',
      dataOutput: '下一节课提示、Today 视图、课程下的任务。',
      faultTolerance: '组件失效时仍可在 App 内快速查看当天内容。',
      coldStartStrategy: '靠“无账号、无广告、无内购”的安心感卖单。',
      pricingLogic: '付费下载一次性收费。',
      competitorDelta: '别人堆功能，这里只关心能不能在锁屏上看到。',
      riskNotes: '情况集中在学生端，需要足够很的使用频率。',
      expansionSteps: ['备考版', '值班表版', '亲子课程版'],
      reverseIdeas: ['作业随课走', '带啥清单', '会议随会走'],
    },
    assets: {
      hasAgentsTemplate: true,
      hasSpecTemplate: true,
      hasPromptPack: false,
      agentsTemplate: '# LiteSchedule AGENTS\n专注课表、提醒和系统入口。',
      specTemplate: '# LiteSchedule SPEC\n课程、提醒、待办三步。',
    },
  },
  {
    slug: 'xiaoshipin-yasuo',
    name: '小视频压缩',
    tagline: '把视频太大发不出去，变成一键压到可用分享。',
    saveTimeLabel: '一键压缩解决分享前的卡点，让视频立刻能发。',
    category: '兴趣创作',
    pricing: PricingModel.PAID,
    channels: ['App Store', '口碑搜索'],
    targetPersona: '需要快速分享视频的普通用户和轻度创作者',
    hookAngle: '必须很直白，胜负点是稳定和顺手。',
    trustSignals: ['App Store 上架'],
    difficulty: 2,
    heatScore: 44,
    screenshotUrls: [
      '/assets/projects/xiaoshipin-yasuo/screenshot-1.jpg',
      '/assets/projects/xiaoshipin-yasuo/screenshot-2.jpg',
      '/assets/projects/xiaoshipin-yasuo/screenshot-3.jpg',
      '/assets/projects/xiaoshipin-yasuo/screenshot-4.jpg',
      '/assets/projects/xiaoshipin-yasuo/screenshot-5.jpg',
    ],
    teardown: {
      painSummary: '视频太大发不出去，很多人又不会调参数。',
      painScore: '大频 / 大痛 / 很必须',
      triggerScene: '视频太大发不出去。',
      corePromise: '在分享前一步，一键压缩到可发送。',
      coreLoop: '选视频 -> 一键压缩 -> 立就是分享 -> 下次继续使用。',
      keyConstraints: ['稳定', '足够快', '结果可控'],
      mvpScope: '自动压缩、快捷压缩、专业模式。',
      dataInput: '视频文件、压缩目标。',
      dataOutput: '压缩后视频、体积信息、分享动作。',
      faultTolerance: '压缩失败时保留原视频并提示降级模式。',
      coldStartStrategy: '靠搜索流量吃掉明确的“压缩”需求。',
      pricingLogic: '付费下载。',
      competitorDelta: '用三档模式包括从小白到专业用户。',
      riskNotes: '稳定性是生死线，闪退会直接毁掉口碑。',
      expansionSteps: ['批量压缩', '分享扩展', '离线隐私压缩'],
      reverseIdeas: ['一键可用分享', '三档模式', '创作者批量压缩'],
    },
    assets: {
      hasAgentsTemplate: true,
      hasSpecTemplate: true,
      hasPromptPack: false,
      agentsTemplate: '# 小视频压缩 AGENTS\n专注视频输入、压缩和分享。',
      specTemplate: '# 小视频压缩 SPEC\n输入、模式、输出、分享流程。',
    },
  },
  {
    slug: 'atvtools',
    name: 'atvTools',
    tagline: '把 ADB 工具装进手机，用 iPhone 管 Android TV。',
    saveTimeLabel: '把复杂维护操作压成一排按钮，降小折腾门槛。',
    category: '居家生活',
    pricing: PricingModel.PAID,
    channels: ['App Store', '技术圈'],
    targetPersona: 'Android TV 喜欢折腾的人和家庭设备维护用户',
    hookAngle: '把极客命令变成普通人也能点的按钮。',
    trustSignals: ['App Store 上架'],
    difficulty: 3,
    heatScore: 57,
    screenshotUrls: [
      '/assets/projects/atvtools/screenshot-1.jpg',
      '/assets/projects/atvtools/screenshot-2.jpg',
      '/assets/projects/atvtools/screenshot-3.jpg',
      '/assets/projects/atvtools/screenshot-4.jpg',
      '/assets/projects/atvtools/screenshot-5.jpg',
      '/assets/projects/atvtools/screenshot-6.jpg',
    ],
    teardown: {
      painSummary: '电视出问题要敲命令，普通人根本搞不定。',
      painScore: '中频 / 大痛 / 明确人群',
      triggerScene: '电视卡顿、装应用或要传文件时，用户需要快速处理。',
      corePromise: '用手机就能一键完成 Android TV 常见维护动作。',
      coreLoop: '连接设备 -> 一键维护 -> 电视恢复正常 -> 下次出问题再回来。',
      keyConstraints: ['连接稳定', '按钮直观', '结果可见'],
      mvpScope: '清缓存、重启、截图录屏、文件传输。',
      dataInput: '设备连接信息、操作指令。',
      dataOutput: '维护结果、监控信息、传输完成状态。',
      faultTolerance: '连接失败时用向导回退，操作失败时给明确提示。',
      coldStartStrategy: '靠“每个 Android TV 用户都这个有”的定位切极客人群。',
      pricingLogic: '付费下载。',
      competitorDelta: '别人要敲命令，这里点按钮就行。',
      riskNotes: '目标人群较窄，连接引导做不好会直接流失。',
      expansionSteps: ['小白引导版', '家庭设备管家', '更轻的五按钮版'],
      reverseIdeas: ['手机管电视', '一键维护', '小白连接向导'],
    },
    assets: {
      hasAgentsTemplate: true,
      hasSpecTemplate: true,
      hasPromptPack: false,
      agentsTemplate: '# atvTools AGENTS\n专注连接、维护和按钮化操作。',
      specTemplate: '# atvTools SPEC\n设备连接、命令、结果反馈三步。',
    },
  },
  {
    slug: 'lovekey-keyboard',
    name: 'Lovekey 键盘',
    tagline: '把恋爱聊天里的尴尬回复，前移成键盘内的一键生成。',
    saveTimeLabel: '不离开聊天界面，直接在键盘里完成回复建议和分寸控制。',
    category: '关系沟通',
    pricing: PricingModel.FREEMIUM,
    channels: ['App Store', 'iOS 键盘扩展', '订阅会员'],
    targetPersona: '在暧昧、恋爱和陌生人破冰情况里，容易卡在“这个怎么回”的用户',
    hookAngle: '把 AI 回复从独立工具前移到键盘入口，再用亲密度和人设把回复包装成“更会聊”。',
    trustSignals: ['App Store 4.4 分 / 4.6 万评分', '服务协议和隐私协议公开', 'iOS 键盘扩展入口'],
    difficulty: 3,
    heatScore: 76,
    screenshotUrls: [
      '/assets/projects/lovekey-keyboard/screenshot-1.jpg',
      '/assets/projects/lovekey-keyboard/screenshot-2.jpg',
      '/assets/projects/lovekey-keyboard/screenshot-3.jpg',
      '/assets/projects/lovekey-keyboard/screenshot-4.jpg',
    ],
    teardown: {
      painSummary: '聊天最难的不是说什么，而是怕说错话、说太冷或者太热情。',
      painScore: '大频 / 大情绪波动 / 很就是时性',
      triggerScene: '用户在恋爱、暧昧和陌生人聊天里看到消息，想立刻回，但怕说错、说冷或显得太用力。',
      corePromise: '复制对话后直接唤起键盘，在聊天现场一键给出更贴近关系阶段的回复建议。',
      coreLoop: '收到消息 -> 复制对话 -> 键盘生成回复 -> 按亲密度或人设微调 -> 发出消息 -> 下次继续依赖键盘入口。',
      keyConstraints: ['必须足够快', '不能跳出聊天情况', '回复要有分寸感而不是统一口吻'],
      mvpScope: '对话复制、一键回复、亲密度控制、人设模板。',
      dataInput: '聊天上下文、关系阶段、用户选定的人设和亲密度。',
      dataOutput: '可直接发送的候选回复、不同语气版本、开场白建议。',
      faultTolerance: '生成不准时允许快速重刷和切换亲密度，避免一次错误建议直接毁掉信任。',
      coldStartStrategy: '用“恋爱聊天神器”“不知道怎么回消息也能聊”这类很情绪问题在应用商店和内容平台吸引首批用户。',
      pricingLogic: '免费入口 + 订阅会员解锁全部功能和持续更新。',
      competitorDelta: '不是通用 AI 助手，而是把回复生成前移到键盘里，并用亲密度和人设把“分寸感”做成设置选项。',
      riskNotes: '如果建议过于方法、失真或显得像复制粘贴，会快速伤害用户信任；同时恋爱情况内容安全和价值观边界更敏感。',
      expansionSteps: ['职场分寸回复版', '长辈沟通版', '群聊语气修正版'],
      reverseIdeas: ['键盘内就是时 AI', '按关系阶段调整', '模板市场驱动复用'],
    },
    assets: {
      hasAgentsTemplate: true,
      hasSpecTemplate: true,
      hasPromptPack: false,
      agentsTemplate: '# Lovekey AGENTS\n专注聊天上下文、分寸控制和键盘内生成回复。',
      specTemplate: '# Lovekey SPEC\n键盘入口、对话复制、关系档位、人设模板四步。',
    },
  },
  {
    slug: 'biubiubiu-air-gun',
    name: 'BiuBiuBiu - 空气枪',
    tagline: '把手机和手表变成抬手就响的空气枪玩具。',
    saveTimeLabel: '用动作和音效把手机从屏幕工具变成就是时可玩的体感玩具。',
    category: '轻娱乐',
    pricing: PricingModel.PAID,
    channels: ['App Store', 'Apple Watch', '体感玩具'],
    targetPersona: '喜欢搞怪、聚会互动和手表小玩具的轻娱乐用户',
    hookAngle: '不是复杂游戏，而是把“抬手开枪”这个动作直接做成随时可玩的就是时反馈。',
    trustSignals: ['App Store 4.8 分 / 6962 评分', '支持 Apple Watch', '持续更新武器和节日方式'],
    difficulty: 2,
    heatScore: 61,
    screenshotUrls: [
      '/assets/projects/biubiubiu-air-gun/screenshot-1.png',
      '/assets/projects/biubiubiu-air-gun/screenshot-2.png',
      '/assets/projects/biubiubiu-air-gun/screenshot-3.png',
      '/assets/projects/biubiubiu-air-gun/screenshot-4.png',
      '/assets/projects/biubiubiu-air-gun/screenshot-5.png',
      '/assets/projects/biubiubiu-air-gun/screenshot-6.png',
    ],
    teardown: {
      painSummary: '很多人想要一个不用学规则、抬手就能逗乐别人的轻量互动玩具。',
      painScore: '大频碎片 / 小门槛 / 很就是时反馈',
      triggerScene: '用户在无聊、聚会或临时搞怪时，想立刻拿出一个动作就能见效的小玩具。',
      corePromise: '把举枪姿势、震动和枪械音效绑在一起，让手机和手表瞬间变成空气枪。',
      coreLoop: '打开 App -> 选武器 -> 抬手或摆姿势 -> 听到反馈 -> 换武器继续玩。',
      keyConstraints: ['反馈必须就是时', '武器切换要简单', '手表和手机都要顺手'],
      mvpScope: '枪械音效、武器切换、手表联动、基础动作触发。',
      dataInput: '手势动作、设备姿态、武器选择。',
      dataOutput: '枪声、上膛声、震动反馈和就是时娱乐效果。',
      faultTolerance: '动作识别不稳定时也要保底支持点击触发，避免当场冷掉。',
      coldStartStrategy: '靠 App Store 截图和短视频式搞怪演示，切中“抬手就能玩”的小解释成本。',
      pricingLogic: '小价付费下载，靠持续补武器和节日方式维持口碑。',
      competitorDelta: '不是对战游戏，而是把手机和手表变成随手能玩的玩具。',
      riskNotes: '方式过轻时容易被玩腻，后续更新如果不持续补新鲜感，留下会掉得很快。',
      expansionSteps: ['双人对射版', '派对音效包', '节日礼花和奇怪武器包'],
      reverseIdeas: ['手机变玩具', '动作触发音效', '手表联动搞怪'],
    },
    assets: {
      hasAgentsTemplate: true,
      hasSpecTemplate: true,
      hasPromptPack: false,
      agentsTemplate: '# BiuBiuBiu AGENTS\n专注动作触发、音效反馈和手表联动。',
      specTemplate: '# BiuBiuBiu SPEC\n武器切换、动作触发、反馈和手机和手表联动四步。',
    },
  },
  {
    slug: 'hunqi',
    name: '婚启',
    tagline: '把备婚清单、预算、日期和回忆放进同一个情侣一起工具里。',
    saveTimeLabel: '让备婚这件碎而杂的事，能被两个人一起看见、一起推进。',
    category: '关系沟通',
    pricing: PricingModel.PAID,
    channels: ['App Store', '情侣一起', '婚礼筹备'],
    targetPersona: '正在备婚、需要一起分工和控预算的情侣',
    hookAngle: '不是单点婚礼工具，而是把备婚全流程做成双人一起台。',
    trustSignals: ['App Store 上架', '包括备婚全流程模块', '礼金簿和座位表等工具内置'],
    difficulty: 3,
    heatScore: 58,
    screenshotUrls: [],
    teardown: {
      painSummary: '备婚最累的不是单个决定，而是任务、预算、日期和回忆同时分散在不同地方。',
      painScore: '中大频 / 大协调成本 / 很双人协作',
      triggerScene: '情侣开始进入备婚阶段，需要一起推进场地、摄影、预算和礼金等繁杂事项。',
      corePromise: '让两人一起管理婚礼准备，从任务到预算再到回忆都能同步推进。',
      coreLoop: '设婚期 -> 自动排期 -> 分工推进任务 -> 记录支出和回忆 -> 反复回来看进度。',
      keyConstraints: ['双人一起要顺', '信息不能散', '预算和时间必须清楚'],
      mvpScope: '婚礼倒计时、任务一起、预算记录、礼金簿和座位表。',
      dataInput: '婚期、任务清单、预算项、亲友名单、回忆素材。',
      dataOutput: '筹备进度、预算统计、礼金记录、座位安排和回忆时间轴。',
      faultTolerance: '一起同步失败时至少保住本地记录，避免把备婚流程打断。',
      coldStartStrategy: '用“情侣一起备婚”“一个 App 管全流程”切中明确阶段需求。',
      pricingLogic: '小价付费下载，靠阶段性很需求变成付费用户。',
      competitorDelta: '不是某一个备婚小工具，而是把任务、预算、礼金和回忆都装进同一个一起视图。',
      riskNotes: '备婚是特定阶段才需要，用一阵子就不用了，必须把筹备密度大的几个月服务好。',
      expansionSteps: ['宝宝筹备版', '搬家一起版', '周年纪念计划版'],
      reverseIdeas: ['情侣一起筹备', '预算和任务联动', '阶段型关系项目管理'],
    },
    assets: {
      hasAgentsTemplate: true,
      hasSpecTemplate: true,
      hasPromptPack: false,
      agentsTemplate: '# 婚启 AGENTS\n专注情侣一起、备婚流程和预算推进。',
      specTemplate: '# 婚启 SPEC\n婚期、任务、预算、礼金和回忆五层结构。',
    },
  },
  {
    slug: 'air-basketball',
    name: '空气投篮',
    tagline: '把抬手投篮的空气动作，变成手表和手机都能回应的就是时爽感。',
    saveTimeLabel: '让一个原本只有自己懂的空气投篮动作，终于能被系统认真接住。',
    category: '轻娱乐',
    pricing: PricingModel.PAID,
    channels: ['App Store', 'Apple Watch', '运动搞怪'],
    targetPersona: '爱篮球、爱搞怪、会下意识做投篮动作的人',
    hookAngle: '不是体育记录工具，而是把“空气投篮”这种无实体动作做成可回响的互动玩具。',
    trustSignals: ['App Store 4.3 分 / 4306 评分', '支持 Apple Watch', '多种运动和方式持续更新'],
    difficulty: 2,
    heatScore: 72,
    screenshotUrls: [
      '/assets/projects/air-basketball/screenshot-1.png',
      '/assets/projects/air-basketball/screenshot-2.png',
      '/assets/projects/air-basketball/screenshot-3.png',
      '/assets/projects/air-basketball/screenshot-4.png',
      '/assets/projects/air-basketball/screenshot-5.png',
      '/assets/projects/air-basketball/screenshot-6.png',
    ],
    teardown: {
      painSummary: '很多人会下意识做投篮动作，但这个动作一直没有被世界回应过。',
      painScore: '大频碎片 / 很情绪代入 / 就是时爽感',
      triggerScene: '用户在无聊、工作间隙或情绪上头时，忍不住对着空气完成一次投篮出手。',
      corePromise: '识别投篮手势动作，并用逼真的空心入网声把这次空气出手变成真的命中反馈。',
      coreLoop: '佩戴手表 -> 做出投篮动作 -> 听到入网音效 -> 连投几次 -> 分享给同好或继续挑战。',
      keyConstraints: ['动作识别要稳', '入网反馈要爽', '佩戴和上手不能麻烦'],
      mvpScope: '投篮识别、空心音效、手表联动、基础方式包。',
      dataInput: '手势动作、手表姿态、当前方式模式。',
      dataOutput: '命中音效、震动反馈、方式结果和连续出手体验。',
      faultTolerance: '识别不准时要快速回退到更宽松的动作阈值，避免“我明明投了却没反应”。',
      coldStartStrategy: '用“空气投篮终于有回应了”这种小解释成本文案切篮球喜欢篮球的人。',
      pricingLogic: '小价付费下载，靠持续更新方式和主题维持新鲜感。',
      competitorDelta: '不是健身工具，而是让虚拟动作有真实的反馈。',
      riskNotes: '如果声音反馈和识别精度撑不起预期，情怀吸引力会迅速失效。',
      expansionSteps: ['多人比拼版', '训练命中节奏版', '更多球类动作包'],
      reverseIdeas: ['空气动作也有回响', '空心入网反馈', '运动情怀玩具'],
    },
    assets: {
      hasAgentsTemplate: true,
      hasSpecTemplate: true,
      hasPromptPack: false,
      agentsTemplate: '# 空气投篮 AGENTS\n专注动作识别、命中反馈和手表联动。',
      specTemplate: '# 空气投篮 SPEC\n动作输入、命中音效、方式模式和设备联动四步。',
    },
  },
  {
    slug: 'cat-language',
    name: '猫咪语言',
    tagline: '把猫叫声、人格测试和轻互动小游戏装成一个喵系内容入口。',
    saveTimeLabel: '让“逗猫、测猫、看猫”这几种轻需求不用分散在不同 App 里。',
    category: '宠物陪伴',
    pricing: PricingModel.PAID,
    channels: ['App Store', '宠物内容', '猫奴社群'],
    targetPersona: '喜欢猫、想逗猫或爱做宠物人格测试的轻宠物用户',
    hookAngle: '不只讲“听懂猫”，而是把猫叫声、测试和剧情内容都做成可玩的猫咪内容集合。',
    trustSignals: ['App Store 上架', '含猫叫互动、人格测试和剧场内容', '小价轻内容入口'],
    difficulty: 2,
    heatScore: 41,
    screenshotUrls: [],
    teardown: {
      painSummary: '很多猫咪相关需求都很轻，但用户希望在一个地方完成互动、测试和内容消遣。',
      painScore: '大频碎片 / 轻决策 / 内容为主',
      triggerScene: '用户想和猫互动、想拿猫做个测试，或者只是想刷一点有趣内容。',
      corePromise: '把猫叫声、喵星人格测试和猫咪剧场整合成一个轻量入口，让用户随手就能开始玩。',
      coreLoop: '打开 App -> 选互动或测试 -> 获得结果或反应 -> 再尝试别的方式 -> 分享或继续刷内容。',
      keyConstraints: ['入口轻', '内容要足够萌', '测试和互动不能太复杂'],
      mvpScope: '猫叫声互动、人格测试、猫咪剧场、基础小游戏。',
      dataInput: '用户选择的方式、测试答案、互动按钮操作。',
      dataOutput: '叫声反馈、测试结果、剧情内容和轻互动体验。',
      faultTolerance: '方式单个不够深时，要靠多个轻内容模块彼这个补位，避免一下玩空。',
      coldStartStrategy: '用“更懂猫”“喵星人格测试”这种轻内容标题在猫奴和泛娱乐用户里拉新。',
      pricingLogic: '小价付费下载，走轻内容聚合路线。',
      competitorDelta: '不是专业工具，而是把和猫相关的小内容和小游戏放在一起。',
      riskNotes: '如果内容更新慢或方式太浅，用户会很快把它当一次性娱乐 App。',
      expansionSteps: ['猫咪表情包生成', '多猫人格组合', '宠物短剧和节日主题包'],
      reverseIdeas: ['宠物互动内容合集', '人格测试入口', '轻内容聚合'],
    },
    assets: {
      hasAgentsTemplate: true,
      hasSpecTemplate: true,
      hasPromptPack: false,
      agentsTemplate: '# 猫咪语言 AGENTS\n专注宠物互动、测试内容和轻娱乐体验。',
      specTemplate: '# 猫咪语言 SPEC\n互动、测试、剧场和小游戏四步。',
    },
  },
  {
    slug: 'watch-browser',
    name: '手表浏览器',
    tagline: '把网页入口前移到手表上，抬腕就能搜、看和点。',
    saveTimeLabel: '让原本要在手机上做的动作，在手表上完成。',
    category: '效率工具',
    pricing: PricingModel.PAID,
    channels: ['App Store', 'Apple Watch', '手表工具'],
    targetPersona: '想在手表上快速搜信息、开常用网页或做简单浏览的人',
    hookAngle: '不是把浏览器做全，而是把最常用的网页入口硬塞进腕上入口层。',
    trustSignals: ['App Store 3.5 分 / 792 评分', '支持 watchOS 8', '支持音视频流和常用站点预设'],
    difficulty: 3,
    heatScore: 52,
    screenshotUrls: ['/assets/projects/watch-browser/screenshot-1.jpg'],
    teardown: {
      painSummary: '很多轻网页动作它的实只想抬腕看一眼，但传统浏览器必须掏手机才能完成。',
      painScore: '大频碎片 / 小时长 / 入口价值很',
      triggerScene: '用户不想掏手机，只想在腕上快速搜一个词、开一个常用网页或看一眼结果。',
      corePromise: '让搜索和浏览在手表上完成，不再依赖手机中转。',
      coreLoop: '抬腕 -> 打开预设站点或搜索 -> 看结果 -> 下次继续在腕上完成简单浏览。',
      keyConstraints: ['输入不能太痛苦', '常用站点要够近', '页面显示要能看'],
      mvpScope: '搜索引擎切换、常用站点预设、自定义首页标签、基础音视频播放。',
      dataInput: '搜索词、预设站点、首页标签。',
      dataOutput: '网页结果、常用页面入口、简单浏览体验。',
      faultTolerance: '复杂页面打不开时，也要保住最基础的搜索和常用站点访问功能。',
      coldStartStrategy: '用“手表也能上网”这种反直觉卖点吸引手表工具和尝鲜用户。',
      pricingLogic: '小价付费下载，满足明确的手表上的需求。',
      competitorDelta: '不是完整浏览器，而是把网页塞到手表小屏幕里。',
      riskNotes: '如果输入、渲染和常用情况不够顺，用户会迅速回到手机端。',
      expansionSteps: ['快捷片段阅读版', '腕上收藏夹', '常用工具站点市场'],
      reverseIdeas: ['手表直接开网页', '预设常用站点', '腕上搜索入口'],
    },
    assets: {
      hasAgentsTemplate: true,
      hasSpecTemplate: true,
      hasPromptPack: false,
      agentsTemplate: '# 手表浏览器 AGENTS\n专注腕上网页入口、常用站点和简单浏览体验。',
      specTemplate: '# 手表浏览器 SPEC\n搜索、预设站点、自定义首页和简单浏览四步。',
    },
  },
  {
    slug: 'plate-simulator',
    name: '车牌模拟器',
    tagline: '把车牌选号、样式生成和违章查询压成一个就是时预览工具。',
    saveTimeLabel: '选号前先看看效果。',
    category: '效率工具',
    pricing: PricingModel.PAID,
    channels: ['App Store', '选号情况', '车主工具'],
    targetPersona: '准备上牌、想试车牌样式或有摩托车牌照需求的车主用户',
    hookAngle: '不是资料型工具，而是把车牌想象直接变成可保存的就是时预览。',
    trustSignals: ['App Store 上架', '支持燃油车 / 新能源 / 摩托车', '支持大清保存'],
    difficulty: 2,
    heatScore: 47,
    screenshotUrls: [
      '/assets/projects/plate-simulator/screenshot-1.png',
      '/assets/projects/plate-simulator/screenshot-2.png',
      '/assets/projects/plate-simulator/screenshot-3.png',
    ],
    teardown: {
      painSummary: '很多人选号时它的实想先看看“长什么样”，但真实流程里缺少一个快速试样和比较的地方。',
      painScore: '中频 / 小学习成本 / 很结果导向',
      triggerScene: '用户准备上牌或临时想试一个号码组合，想先看到实际车牌效果再决定。',
      corePromise: '快速生成不同车牌样式，让用户先看结果，再决定怎么选。',
      coreLoop: '输入号码 -> 生成样式 -> 比较保存 -> 再试下一组号码或延伸到查询情况。',
      keyConstraints: ['生成要快', '样式要像真的', '保存分享足够顺手'],
      mvpScope: '多车型车牌生成、大清保存、基础选号和违章查询入口。',
      dataInput: '车型、号码组合、车牌类型。',
      dataOutput: '可视化车牌样式、保存图、选号辅助结果。',
      faultTolerance: '就是使查询功能差，也要保证生成和预览这条主路径始终可用。',
      coldStartStrategy: '用“先看看你的车牌长什么样”这种小解释成本切选号情况。',
      pricingLogic: '小价付费下载，满足明确的小情况需求。',
      competitorDelta: '不是查数据库，而是让你先看看效果长什么样。',
      riskNotes: '情况偏窄，若生成效果不够真实或可比性不很，用户很难形成复用。',
      expansionSteps: ['个性号牌风格包', '多方法对比版', '车主小工具集合'],
      reverseIdeas: ['结果先预览', '多方法对比', '小情况生成器'],
    },
    assets: {
      hasAgentsTemplate: true,
      hasSpecTemplate: true,
      hasPromptPack: false,
      agentsTemplate: '# 车牌模拟器 AGENTS\n专注车牌生成、样式预览和结果保存。',
      specTemplate: '# 车牌模拟器 SPEC\n车型选择、号码生成、样式预览和保存四步。',
    },
  },
];

export type IdeaV2Seed = {
  title: string;
  note: string;
  category: string;
  tags: string[];
  votes: number;
  featured: boolean;
  isNovel: boolean;
  novelReason?: string;
  novelTicks: string[];
  evidence?: Array<{
    sourceAppSlug?: string;
    appTitle: string;
    appUrl: string;
    platform: string;
    how: string;
    cpHook: string;
    cpWow: string;
    cpReturn: string;
  }>;
};

export const v2IdeaSeeds: IdeaV2Seed[] = [
  {
    title: '私密行为地图打点',
    category: 'home',
    tags: ['记录', '地图', '隐秘但好玩'],
    votes: 82,
    featured: true,
    isNovel: true,
    novelReason: '把尴尬小事做成战绩收集，这个反差很抓人',
    novelTicks: ['壳子新', '组合新', '结果新'],
    note: '来源 App: Poop Map\n背景: 只是想记个小事，但纯记录太干，几天就弃用。\n亮点: 点一下就有新战绩，会上头，真的会。\nRoom:\n- 尴尬但上头的私密地图\n- 战绩收集挑战版',
    evidence: [
      {
        sourceAppSlug: 'poop-map',
        appTitle: 'Poop Map',
        appUrl: 'https://play.google.com/store/apps/details?id=net.poopmap',
        platform: 'Google Play',
        how: '它不是在做“记录”，是在做“收集”。每点一次就像多拿一枚徽章。',
        cpHook: '第一眼我记住的是那句直球文案，没解释成本。',
        cpWow: '点完立刻落到地图上，这一下反馈很爽。',
        cpReturn: '隔几天会忍不住再看一眼自己的地图长啥样。',
      },
    ],
  },
  {
    title: '地图打点社交',
    category: 'social',
    tags: ['好友圈', '轻社交'],
    votes: 75,
    featured: true,
    isNovel: true,
    novelReason: '不靠长内容，靠一个小动作就能把社交拉起来',
    novelTicks: ['壳子新', '方法新'],
    note: '来源 App: Poop Map\n背景: 平时想互动一下，但没人想写长段子。\n亮点: 你打一条点，朋友点个赞，互动就发生了。\nRoom:\n- 任何小事都能打点的圈子\n- 好友挑战榜',
  },
  {
    title: '锁屏倒计时',
    category: 'work',
    tags: ['倒计时', '纪念日', '锁屏常驻'],
    votes: 68,
    featured: true,
    isNovel: true,
    novelReason: '倒计时从“要去找”变成“抬眼就看见”',
    novelTicks: ['入口新', '结果新'],
    note: '来源 App: Countdown! Reminders and Timer\n背景: 你它的实在意那个日子，但总要点进 App 才看得到。\n亮点: 放到锁屏后，不提醒也会每天看到。\nRoom:\n- 会议倒计时墙\n- 项目里程碑墙',
    evidence: [
      {
        sourceAppSlug: 'countdown-reminders-and-timer',
        appTitle: 'Countdown! Reminders and Timer',
        appUrl: 'https://apps.apple.com/us/app/countdown-reminders-and-timer/id1439723850',
        platform: 'App Store',
        how: '重点不在算天数，而在“倒计时被塞进系统入口”。',
        cpHook: '我第一眼被吸引的是组件够多，想怎么摆都行。',
        cpWow: '建完事件，锁屏马上就开始动。',
        cpReturn: '不是主动回访，是每天解锁手机都会撞见它。',
      },
    ],
  },
  {
    title: '时间进度条',
    category: 'work',
    tags: ['进度条', '时间焦虑'],
    votes: 54,
    featured: false,
    isNovel: true,
    novelReason: '看见百分比在掉，比一句“快点做”更有效',
    novelTicks: ['结果新'],
    note: '来源 App: Countdown! Reminders and Timer\n背景: 截止日看起来还远，人就会拖。\n亮点: 百分比每次一看都在变，拖延感会被戳破。\nRoom:\n- 时间进度分享卡',
  },
  {
    title: '课表常驻显示',
    category: 'school',
    tags: ['课表', '抬眼就看', '常驻'],
    votes: 63,
    featured: true,
    isNovel: true,
    novelReason: '课表这种大频信息，应这个放在系统入口而不是二级页面',
    novelTicks: ['入口新', '组合新'],
    note: '来源 App: LiteSchedule\n背景: 课间跑教室时，真的没空一层层点进去查课表。\n亮点: 抬眼就知道下节课，省下的不是 1 秒，是费脑子。\nRoom:\n- 校园抬眼工具\n- 极简课表 v0',
    evidence: [
      {
        sourceAppSlug: 'liteschedule',
        appTitle: 'LiteSchedule',
        appUrl: 'https://apps.apple.com/tw/app/liteschedule/id6759214053',
        platform: 'App Store',
        how: '先把“找课表”这步砍掉，使用频次自然上来。',
        cpHook: '我会记住它是因为够干净，没有乱七八糟打扰。',
        cpWow: '当天课程一下就能看到，几乎零学习。',
        cpReturn: '每天上学都会用，不需要培养习惯。',
      },
    ],
  },
  {
    title: '课程作业联动',
    category: 'school',
    tags: ['作业', '待办'],
    votes: 48,
    featured: true,
    isNovel: true,
    novelReason: '把“哪门课 + 哪个作业”绑在一起，费脑子立刻降下来',
    novelTicks: ['组合新'],
    note: '来源 App: LiteSchedule\n背景: 课表在一个地方，作业在另一个地方，最后就是漏交。\n亮点: 点进这门课就看到这门课要做什么，脑子清爽很多。\nRoom:\n- DDL 雷达\n- 备考科目版',
  },
  {
    title: '视频压缩',
    category: 'hobby',
    tags: ['压缩', '分享'],
    votes: 44,
    featured: true,
    isNovel: false,
    novelTicks: [],
    note: '来源 App: 小视频压缩\n背景: 不是天天压缩，但一到要发客户/群里就卡在“文件太大”。\n亮点: 先发出去，画质用后再调，这个顺序很真实。\nRoom:\n- 分享前一步压缩\n- 创作者批量压缩',
    evidence: [
      {
        sourceAppSlug: 'xiaoshipin-yasuo',
        appTitle: '小视频压缩',
        appUrl: 'https://apps.apple.com/cn/app/%E5%B0%8F%E8%A7%86%E9%A2%91%E5%8E%8B%E7%BC%A9/id1480567274',
        platform: 'App Store',
        how: '它抓得很准：先解“发不出去”，再谈精细化。',
        cpHook: '第一眼就是那个问题，几乎不用教育。',
        cpWow: '自动模式够快，救急情况能顶住。',
        cpReturn: '只要还在发视频，它就有再用机会。',
      },
    ],
  },
  {
    title: '压缩参数三档',
    category: 'hobby',
    tags: ['三档模式', '专业参数'],
    votes: 33,
    featured: false,
    isNovel: false,
    novelTicks: [],
    note: '来源 App: 小视频压缩\n背景: 新手不敢碰参数，熟手又嫌“一键”太傻。\n亮点: 三档模式让两拨人都能找到自己的默认操作。\nRoom:\n- 隐私本地压缩\n- 批量队列压缩',
  },
  {
    title: '使用手机做电视遥控器',
    category: 'home',
    tags: ['电视', '工具', '极客'],
    votes: 57,
    featured: true,
    isNovel: true,
    novelReason: '原来要连电脑敲命令，现在手机上点几下就能做',
    novelTicks: ['组合新', '结果新'],
    note: '来源 App: atvTools\n背景: 遥控器经常不在手边，家里设备又不止一台。\n亮点: 手机本来就在手上，直接顶上遥控器角色。\nRoom:\n- 更轻的电视助手\n- 小白引导版\n- 家庭设备管家',
    evidence: [
      {
        sourceAppSlug: 'atvtools',
        appTitle: 'atvTools',
        appUrl: 'https://apps.apple.com/us/app/atvtools/id1661419573',
        platform: 'App Store',
        how: '先把大频 5 个动作按钮化，别一上来就搞全功能。',
        cpHook: '“手机管电视”这个定位一秒懂。',
        cpWow: '配置好后点击就能做，反馈够直。',
        cpReturn: '每次电视出问题，它都会被想起来。',
      },
    ],
  },
  {
    title: '电视一键维护',
    category: 'home',
    tags: ['一键维护'],
    votes: 41,
    featured: false,
    isNovel: true,
    novelReason: '把“诊断”变成“先救急”，使用门槛会小很多',
    novelTicks: ['结果新'],
    note: '来源 App: atvTools\n背景: 真遇到卡顿时，用户只想先恢复，不想学概念。\n亮点: 先救急，再慢慢排查，这个体验顺序对了。\nRoom:\n- 家庭设备 5 按钮\n- 小白配对向导',
  },
  {
    title: '下节课携带提醒',
    category: 'school',
    tags: ['抬眼提示', '携带清单'],
    votes: 22,
    featured: false,
    isNovel: true,
    novelReason: '把提醒压到 10 秒可读，信息密度刚刚好',
    novelTicks: ['入口新'],
    note: '待认领变体\n背景: 课间最容易漏带东西，发现时已经进教室了。\n亮点: 只给一眼能读完的信息，不打扰，但有用。\nRoom:\n- 带啥清单',
  },
  {
    title: '吃饭决策倒计时',
    category: 'food',
    tags: ['倒计时', '决策'],
    votes: 19,
    featured: false,
    isNovel: true,
    novelReason: '把“选项过多”变成“倒计时到点就做”',
    novelTicks: ['壳子新', '结果新'],
    note: '待认领变体\n背景: 点外卖前来回滑 15 分钟，是常态。\n亮点: 到点就给答案，先开吃再说。\nRoom:\n- 10 秒吃啥',
  },
  {
    title: '通勤任务卡',
    category: 'commute',
    tags: ['抽卡', '任务', '战绩'],
    votes: 17,
    featured: false,
    isNovel: true,
    novelReason: '把碎片时间从“刷过去”改成“做完一小件”',
    novelTicks: ['壳子新', '组合新'],
    note: '待认领变体\n背景: 一趟通勤 30 分钟，回头看经常啥也没留下。\n亮点: 任务够小，一趟做完一件就算赚到。\nRoom:\n- 通勤任务卡',
  },
];

export type DiscussionThreadSeed = {
  title: string;
  summary: string;
  targetType: 'PROJECT' | 'INCUBATION';
  targetSlug: string;
  createdBy: string;
  openingComment: string;
};

export type IdeaBlockSeed = {
  slug: string;
  title: string;
  summary: string;
  blockType: 'FORMULA' | 'FEATURE' | 'WORKFLOW' | 'CHANNEL';
  tags: string[];
  noveltyNote?: string;
  sourceProjectSlugs: string[];
  sourceThreadTitle?: string;
};

export type IncubationSeed = {
  slug: string;
  title: string;
  oneLiner: string;
  status: 'OPEN' | 'VALIDATING' | 'BUILDING' | 'ARCHIVED';
  createdBy: string;
  sourceProjectSlugs: string[];
  ideaBlockSlugs: string[];
};

export type RoomSeed = {
  slug: string;
  name: string;
  goal: string;
  targetType: 'PROJECT' | 'INCUBATION';
  targetSlug: string;
  createdBy: string;
};

export const discussionSeeds: DiscussionThreadSeed[] = [
  {
    title: 'Poop Map 让人上瘾的是战绩收集，不只是题材猎奇吧？',
    summary: '讨论它的核心到底是反差题材，还是就是时反馈和地图收集。',
    targetType: 'PROJECT',
    targetSlug: 'poop-map',
    createdBy: 'Ming',
    openingComment: '我觉得让人一直玩下去的不是题材本身，而是每次打点都像赢了一局。',
  },
  {
    title: '锁屏倒计时为什么比普通待办更容易被天天看见？',
    summary: '讨论锁屏带来的大频曝光和焦虑管理。',
    targetType: 'PROJECT',
    targetSlug: 'countdown-reminders-and-timer',
    createdBy: 'Luna',
    openingComment: '倒计时工具做得再全，不放到锁屏和桌面，就还是一个被动打开的工具。',
  },
  {
    title: '摸鱼战绩地图会不会比 Poop Map 更容易本土传播？',
    summary: '围绕一个孵化方向讨论情况接受度和表达方式。',
    targetType: 'INCUBATION',
    targetSlug: 'slack-off-map',
    createdBy: 'Aria',
    openingComment: '如果把羞耻感换成职场自嘲，传播门槛可能会更小。',
  },
  {
    title: 'Lovekey 真正能成的，不是 AI 回复，而是把“分寸感”做成设置选项吗？',
    summary: '讨论它的核心竞争力到底是生成功能，还是键盘入口、亲密度和人设模板共同形成的就是时性。',
    targetType: 'PROJECT',
    targetSlug: 'lovekey-keyboard',
    createdBy: 'Ming',
    openingComment: '如果只是会生成回复，它很容易被通用模型替代；真正有优势的可能是把关系阶段和键盘入口一起产品化。',
  },
  {
    title: 'BiuBiuBiu 真正让人想一直玩的，是枪声题材还是触发动作的瞬间吗？',
    summary: '聊它到底靠什么吸引人：是武器多，还是抬手就有反馈的爽感。',
    targetType: 'PROJECT',
    targetSlug: 'biubiubiu-air-gun',
    createdBy: 'Luna',
    openingComment: '这类产品关键的可能不是内容多，而是动作做出来能不能马上得到爽快的反馈。',
  },
  {
    title: '婚启真正难的是，是婚礼工具够全，还是让两个人一直同步推进吗？',
    summary: '讨论备婚类产品的关键到底是模块多，还是双人协作和阶段推进足够顺。',
    targetType: 'PROJECT',
    targetSlug: 'hunqi',
    createdBy: 'Aria',
    openingComment: '备婚不像普通待办，最难的是两个人对同一件事始终看到的是同一个进度。',
  },
  {
    title: '空气投篮最打动人的，是篮球情怀还是空心入网那一下的就是时回响吗？',
    summary: '聊它靠什么吸引人：是篮球情怀，还是动作被识别后的反馈。',
    targetType: 'PROJECT',
    targetSlug: 'air-basketball',
    createdBy: 'Ming',
    openingComment: '这类产品最很的一刻，不一定是方式复杂，而是你一抬手系统就真的懂你在投篮。',
  },
  {
    title: '猫咪语言真正留住人的，会是“懂猫”叙事，还是把测试和互动做成内容入口吗？',
    summary: '聊这类猫咪 App 靠什么留住人：是显得专业，还是把几个小游戏串成一个能玩的地方。',
    targetType: 'PROJECT',
    targetSlug: 'cat-language',
    createdBy: 'Luna',
    openingComment: '如果只是单个猫叫按钮或测试，很容易一会儿就玩完；更关键的可能是把这些轻内容串成连续入口。',
  },
  {
    title: '手表浏览器真正能成的，是“能上网”这个噱头，还是把常用网页入口前移到手腕吗？',
    summary: '聊它到底有什么用：是浏览器功能，还是把网页入口放到抬手就能看到的地方。',
    targetType: 'PROJECT',
    targetSlug: 'watch-browser',
    createdBy: 'Ming',
    openingComment: '如果只是证明手表也能开网页，那很快就会失去新鲜感；更值钱的可能是把最常用的入口前移到手腕。',
  },
  {
    title: '车牌模拟器真正有用的，是查询功能，还是让结果先被看见的就是时预览吗？',
    summary: '讨论它的核心到底是工具信息更全，还是把“先看看效果”这一步做得足够快。',
    targetType: 'PROJECT',
    targetSlug: 'plate-simulator',
    createdBy: 'Aria',
    openingComment: '很多小工具吸引人不是因为功能多，而是能先让人看到结果长什么样。',
  },
];

export const ideaBlockSeeds: IdeaBlockSeed[] = [
  {
    slug: 'private-behavior-map',
    title: '私密行为 x 地图打点',
    summary: '把原本不会被公开表达的小动作，变成能被标记和回看的地图记录。',
    blockType: 'FORMULA',
    tags: ['私密行为', '地图', '记录'],
    noveltyNote: '关键不是记录本身，而是把私密小事变得可以展示。',
    sourceProjectSlugs: ['poop-map'],
    sourceThreadTitle: 'Poop Map 让人上瘾的是战绩收集，不只是题材猎奇吧？',
  },
  {
    slug: 'instant-score-feedback',
    title: '记录动作立就是变战绩反馈',
    summary: '用户动作完成后立刻看到可累计的结果，形成收集和上头感。',
    blockType: 'FEATURE',
    tags: ['就是时反馈', '战绩', '收集'],
    noveltyNote: '就是时反馈比复杂统计更容易制造上头瞬间。',
    sourceProjectSlugs: ['poop-map', 'countdown-reminders-and-timer'],
  },
  {
    slug: 'system-surface-exposure',
    title: '锁屏和桌面直接看结果',
    summary: '不让用户进 App 才看到结果，而是直接把关键状态前置到锁屏、组件或桌面。',
    blockType: 'WORKFLOW',
    tags: ['锁屏', '桌面', '抬眼就看'],
    noveltyNote: '入口被前移后，产品从工具变成日常背景层。',
    sourceProjectSlugs: ['countdown-reminders-and-timer', 'liteschedule'],
  },
  {
    slug: 'light-challenge-loop',
    title: '轻挑战排行榜',
    summary: '用次数、排行榜和轻量比较形成持续回来看的理由。',
    blockType: 'CHANNEL',
    tags: ['社交', '挑战', '排名'],
    sourceProjectSlugs: ['poop-map'],
  },
  {
    slug: 'reply-inside-keyboard-surface',
    title: '键盘内一键生成回复',
    summary: '不让用户跳去独立 App，而是在聊天现场通过键盘扩展直接完成生成、挑选和发送前决策。',
    blockType: 'WORKFLOW',
    tags: ['AI', '键盘', '回复', '聊天'],
    noveltyNote: '真正减少犹豫的不是更很模型，而是让动作发生在消息来回切换的那一秒。',
    sourceProjectSlugs: ['lovekey-keyboard'],
    sourceThreadTitle: 'Lovekey 真正能成的，不是 AI 回复，而是把“分寸感”做成设置选项吗？',
  },
  {
    slug: 'tone-control-by-intimacy',
    title: '按亲密度调节回复语气',
    summary: '通过亲密度控制语气边界，把“怎么回才合适”从隐性经验变成一个可调节的明确动作。',
    blockType: 'FEATURE',
    tags: ['AI', '亲密度', '语气', '聊天'],
    noveltyNote: '这类产品的不是帮你回消息，而是替你掌握分寸。',
    sourceProjectSlugs: ['lovekey-keyboard'],
    sourceThreadTitle: 'Lovekey 真正能成的，不是 AI 回复，而是把“分寸感”做成设置选项吗？',
  },
  {
    slug: 'chat-persona-template-library',
    title: '聊天人设模板市场',
    summary: '把不同聊天风格做成可选模板，让用户不用自己总结语气规则，直接挑一个适合当前关系的人设来用。',
    blockType: 'FEATURE',
    tags: ['AI', '人设', '模板', '聊天'],
    noveltyNote: '一旦人设模板足够丰富，产品卖的就不只是回复功能，而是“我想成为什么样的人”。',
    sourceProjectSlugs: ['lovekey-keyboard'],
    sourceThreadTitle: 'Lovekey 真正能成的，不是 AI 回复，而是把“分寸感”做成设置选项吗？',
  },
  {
    slug: 'motion-triggered-sound-toy',
    title: '手势互动玩具',
    summary: '把抬手、摆姿势这类简单动作和就是时音效绑在一起，让手机和手表都变成可用立刻互动的小玩具。',
    blockType: 'FEATURE',
    tags: ['手势', '互动', '玩具'],
    noveltyNote: '让人想玩的不是规则多复杂，而是做个动作马上就有反馈。',
    sourceProjectSlugs: ['biubiubiu-air-gun'],
    sourceThreadTitle: 'BiuBiuBiu 真正让人想一直玩的，是枪声题材还是触发动作的瞬间吗？',
  },
  {
    slug: 'phone-watch-linked-toy',
    title: '手机和手表一起当玩具',
    summary: '不把手表当通知副屏，而是让手机和手表都能独立参和同一个轻互动方式。',
    blockType: 'WORKFLOW',
    tags: ['手表', '手机', '联动'],
    noveltyNote: '手机和手表联动带来的不是效率，而是更很的“真的拿着东西在玩”的代入感。',
    sourceProjectSlugs: ['biubiubiu-air-gun', 'air-basketball'],
    sourceThreadTitle: 'BiuBiuBiu 真正让人想一直玩的，是枪声题材还是触发动作的瞬间吗？',
  },
  {
    slug: 'weapon-pack-refresh-loop',
    title: '不断更新武器和音效包',
    summary: '用持续新增的武器、节日主题和奇怪音效包维持新鲜感，让轻娱乐产品不至于一周就玩腻。',
    blockType: 'CHANNEL',
    tags: ['武器', '音效包', '新鲜感'],
    noveltyNote: '这类轻玩具的留下不一定靠系统深度，很多时候靠的是“下次又多了什么好玩的”。',
    sourceProjectSlugs: ['biubiubiu-air-gun'],
    sourceThreadTitle: 'BiuBiuBiu 真正让人想一直玩的，是枪声题材还是触发动作的瞬间吗？',
  },
  {
    slug: 'couple-co-planning-board',
    title: '情侣一起筹备清单',
    summary: '把同一阶段要做的事放到一张双人共看的清单里，让分工、提醒和进度始终在同一个视图里推进。',
    blockType: 'WORKFLOW',
    tags: ['情侣', '一起', '清单'],
    noveltyNote: '真正降小消耗的不是任务更多，而是让两个人永远看到同一张筹备面板。',
    sourceProjectSlugs: ['hunqi'],
    sourceThreadTitle: '婚启真正难的是，是婚礼工具够全，还是让两个人一直同步推进吗？',
  },
  {
    slug: 'budget-and-memory-in-one-place',
    title: '预算和回忆放在一起',
    summary: '把支出、礼金和回忆素材都挂在同一个阶段流程里，让重要节点既能复盘花费，也能留下记忆。',
    blockType: 'FEATURE',
    tags: ['预算', '回忆', '阶段管理'],
    noveltyNote: '这不只是记账，而是把算账和记录回忆放在一起。',
    sourceProjectSlugs: ['hunqi'],
    sourceThreadTitle: '婚启真正难的是，是婚礼工具够全，还是让两个人一直同步推进吗？',
  },
  {
    slug: 'motion-shot-feedback',
    title: '动作命中立刻给回响',
    summary: '当用户做出一个熟悉动作后，系统立刻用命中声、震动或节奏反馈把这次动作接住。',
    blockType: 'FEATURE',
    tags: ['动作', '命中', '爽感'],
    noveltyNote: '动作玩具能成的关键，不是识别多复杂，而是反馈够不够准、够不够爽。',
    sourceProjectSlugs: ['air-basketball'],
    sourceThreadTitle: '空气投篮最打动人的，是篮球情怀还是空心入网那一下的就是时回响吗？',
  },
  {
    slug: 'pet-content-playground',
    title: '宠物互动内容合集',
    summary: '把叫声互动、测试、剧场和小游戏放进同一个轻内容入口，让用户每次打开都能很快找到一个可玩点。',
    blockType: 'CHANNEL',
    tags: ['宠物', '内容', '互动'],
    noveltyNote: '这类产品不一定靠单点深度，更像靠内容集合把使用时间拉起来。',
    sourceProjectSlugs: ['cat-language'],
    sourceThreadTitle: '猫咪语言真正留住人的，会是“懂猫”叙事，还是把测试和互动做成内容入口吗？',
  },
  {
    slug: 'cat-personality-test',
    title: '猫咪人格测试入口',
    summary: '用一个足够轻松的测试把用户快速拉进内容，再把后续互动和剧情顺势接上。',
    blockType: 'FEATURE',
    tags: ['猫咪', '测试', '人格'],
    noveltyNote: '测试的作用不一定是准，而是给用户一个马上愿意点进去的起点。',
    sourceProjectSlugs: ['cat-language'],
    sourceThreadTitle: '猫咪语言真正留住人的，会是“懂猫”叙事，还是把测试和互动做成内容入口吗？',
  },
  {
    slug: 'watch-opens-web-entry',
    title: '手表直接打开网页',
    summary: '把原本默认属于手机的网页入口前移到手表，让搜索、常用站点和简单浏览变成抬腕就能做的动作。',
    blockType: 'WORKFLOW',
    tags: ['手表', '网页', '入口'],
    noveltyNote: '这类产品成立的关键，不是功能做全，而是把“不这个在这做的事”硬塞进一个更近的入口。',
    sourceProjectSlugs: ['watch-browser'],
    sourceThreadTitle: '手表浏览器真正能成的，是“能上网”这个噱头，还是把常用网页入口前移到手腕吗？',
  },
  {
    slug: 'preset-sites-on-watch',
    title: '手表预设常用站点',
    summary: '不给用户每次都重新输入，而是先把最常打开的站点固定在首页，减少腕上输入成本。',
    blockType: 'FEATURE',
    tags: ['手表', '预设', '常用站点'],
    noveltyNote: '入口越近，手表工具越像常驻功能，而不是一次性展示功能。',
    sourceProjectSlugs: ['watch-browser'],
    sourceThreadTitle: '手表浏览器真正能成的，是“能上网”这个噱头，还是把常用网页入口前移到手腕吗？',
  },
  {
    slug: 'preview-result-before-decision',
    title: '结果先预览再决定',
    summary: '先把最终样子直接生成出来，让用户在真正做决定前先看到结果，再继续下一步。',
    blockType: 'FEATURE',
    tags: ['预览', '生成', '对比'],
    noveltyNote: '很多小工具有用，不是帮你完成决策，而是先把想象结果的难度降到最小。',
    sourceProjectSlugs: ['plate-simulator'],
    sourceThreadTitle: '车牌模拟器真正有用的，是查询功能，还是让结果先被看见的就是时预览吗？',
  },
  {
    slug: 'small-scene-generator',
    title: '小情况生成器',
    summary: '围绕一个非常具体的瞬时需求，做出输入很短、反馈很快、结果可用直接保存的小生成工具。',
    blockType: 'CHANNEL',
    tags: ['小情况', '生成器', '保存'],
    noveltyNote: '这类工具不靠大而全，靠的是“我现在就想看一下”这一秒足够顺手。',
    sourceProjectSlugs: ['plate-simulator'],
    sourceThreadTitle: '车牌模拟器真正有用的，是查询功能，还是让结果先被看见的就是时预览吗？',
  },
];

export const incubationSeeds: IncubationSeed[] = [
  {
    slug: 'slack-off-map',
    title: '摸鱼战绩地图',
    oneLiner: '把上班偷闲、散步和咖啡出逃做成可记录、可用比较的职场生存战绩。',
    status: 'VALIDATING',
    createdBy: 'Aria',
    sourceProjectSlugs: ['poop-map'],
    ideaBlockSlugs: ['private-behavior-map', 'instant-score-feedback', 'light-challenge-loop'],
  },
  {
    slug: 'meeting-countdown-wall',
    title: '会议倒计时墙',
    oneLiner: '把会议剩余时间、议程进度和提醒前置到锁屏和桌面，降小拖会成本。',
    status: 'OPEN',
    createdBy: 'Luna',
    sourceProjectSlugs: ['countdown-reminders-and-timer', 'liteschedule'],
    ideaBlockSlugs: ['system-surface-exposure', 'instant-score-feedback'],
  },
];

export const roomSeeds: RoomSeed[] = [
  {
    slug: 'slack-off-map-v0',
    name: '摸鱼战绩地图 v0',
    goal: '先试试记录动作、地图展示和轻排行是否能形成最小流程。',
    targetType: 'INCUBATION',
    targetSlug: 'slack-off-map',
    createdBy: 'Aria',
  },
  {
    slug: 'tv-helper-lite',
    name: '更轻的电视助手',
    goal: '把常用五个电视维护动作压成一屏按钮，降小首次连接门槛。',
    targetType: 'PROJECT',
    targetSlug: 'atvtools',
    createdBy: 'Ming',
  },
];
